package com.bankingsim.banking.entity.enums;

public enum TransactionType {
    DEPOSIT,
    WITHDRAW,
    INTERNAL_TRANSFER,
    INTER_BRANCH_TRANSFER,
    BENEFICIARY_TRANSFER,
    EXTERNAL_TRANSFER,
    WALLET_TRANSFER,
    INTEREST_CREDIT,
    SERVICE_CHARGE_DEBIT,
    PENALTY_DEBIT,
    REFUND,
    REVERSAL,
    SCHEDULED_TRANSFER,
    BULK_SALARY_CREDIT,
    FD_CREATION,
    FD_MATURITY_PAYOUT,
    LOAN_EMI_DEBIT,
    RD_INSTALLMENT_DEBIT,
    NEFT,
    IMPS,
    RTGS,
    UPI
}
